update zh_CN
v2fly/v2ray-step-by-step pull request #189
Opened 2020-08-21 06:17 UTC by TATTXT

2020-08-21 15:07 UTC, kslr requested changes

2020-08-21 15:07 UTC, kslr commented on zh_CN/advanced/traffic.md
> +V2Ray 内包含了流量记录器功能，但是默认并不启用。流量统计分三类：`inbound`，`user`和`outbound`（4.25.2+）。
正确的版本应该是 26

2020-08-21 15:07 UTC, kslr commented on zh_CN/basics/dns.md
> +2. 在`dns-in`中设置其它可靠的 DNS 服务器。例如，仅利用 v2ray 内置 DNS 实现 DNS 分流，而解析则使用`dnscrypt-proxy`实现。
中英文之前必须保留空格

2020-08-21 15:07 UTC, kslr commented on zh_CN/prep/install.md
> +**V2ray已经放弃了原来的安装脚本，现在采用新的[fhs-install-v2ray](https://github.com/v2fly/fhs-install-v2ray)项目。**
避免重复描述

2020-08-21 15:07 UTC, kslr commented on zh_CN/prep/install.md
> +SUSE
使用正常不会引起误会的名字

2020-08-21 15:07 UTC, kslr commented on zh_CN/prep/install.md
> +or
使用正常不会引起误会的名字

2020-08-21 15:07 UTC, kslr commented
鉴于这个 PR 的更改大部分是错误的，我建议你重新处理。

2020-08-22 05:31 UTC, TATTXT commented
抱歉，提交的时候没注意到，看起来是我fork的时候版本太久了，我并没有更改上面的部分内容。稍后将作出改正

2020-08-22 05:37 UTC, closed without merging