[WIP]feat(docker deploy): Update deploy document.
v2fly/v2ray-step-by-step pull request #201
Opened 2020-10-19 10:46 UTC by whg517

#200

2020-10-19 10:54 UTC, whg517 commented
Someone code review ?

2020-10-19 11:11 UTC, kslr requested changes
目前出现了不少拼写错误需要纠正再review

2020-10-19 11:11 UTC, kslr commented on zh_CN/app/docker-deploy-v2ray.md
> +> 原文档请移步 [Docker 部署 V2Ray](https://toutyrater.github.io/app/docker-deploy-v2ray.html)
这句话为什么要替换掉呢？

2020-10-19 11:11 UTC, kslr commented on zh_CN/app/docker-deploy-v2ray.md
> +- `/usr/bin/v2ray/geoip.dat`：IP 数据文件
对资源路径重新做了调整

2020-10-19 11:11 UTC, kslr commented on zh_CN/app/docker-deploy-v2ray.md
> +**注意：**一下示例操作环境为 Linux ，Windows 下可能会有区别。
拼写错误

2020-10-19 11:11 UTC, kslr commented on zh_CN/app/docker-deploy-v2ray.md
> +在阅读本内容时，我们假定你已经熟悉 Docker，同时准备好了 Docker 环境。如果你还不熟悉 Docker ，请阅读 [Docker Engine overview](https://docs.docker.com/engine/) 。如果你还没有 Docker 环境，请参考 [Install Docker Engine](https://docs.docker.com/engine/in
这句话感觉有点奇怪，比如 “我们” “阐述如何安装，介绍基本操作”

另外中文和英语逗号最好不要混用

2020-10-19 11:11 UTC, kslr commented on zh_CN/app/docker-deploy-v2ray.md
> +从 [Docker Hub](https://hub.docker.com/r/v2fly/v2fly-core) 拉去镜像。默认当前构建的最新版本镜像( `v2fly/v2ray-core:latest` )，如需使用老版本请在镜像名称后面加版本号，如 `v2fly/v2ray-core:4.27.0`
拼写错误

2020-10-22 08:06 UTC, whg517 commented on zh_CN/app/docker-deploy-v2ray.md
> +> 原文档请移步 [Docker 部署 V2Ray](https://toutyrater.github.io/app/docker-deploy-v2ray.html)
我认为当用户已经开始考虑使用 Docker 来部署服务了，肯定已经了解 Docker 是什么了。如果他还需要通过文章开头的一段简述认识 Docker 的话，文中的操作其实并不适合他，即便照着文档操作成功了，日后维护也依然会让他头大，毕竟 Docker 的技术层次和通过 shell 这种操作来说高太多。

当然如果你希望在文章开头加上一段 Docker 的简述内容，我更愿意摘录 [Docker 文档中的内容](https://docs.docker.com/get-started/overview/)，或者 [wikipedia 中的](https://en.wikipedia.org/wiki/Docker_(software))

2020-11-27 16:59 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> +### 2.1 拉取 V2ray 镜像
R

2020-11-27 16:59 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> +### 3.2 启动 V2ray 服务
R

2020-11-27 16:59 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> +### 3.3 停止 V2ray 服务
R

2020-11-27 16:59 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> +如果不需要 V2ray 了，可以将其删除
R

2020-11-27 17:00 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> +### 3.4 重启 V2ray 服务
R

2020-11-27 17:00 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> +### 2.2 运行 V2ray 服务
R

2020-11-27 17:00 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> +### 2.4 重启 V2ray 服务
R

2020-11-30 10:04 UTC, DuckSoft requested changes

2020-11-30 10:04 UTC, DuckSoft commented on zh_CN/app/docker-deploy-v2ray.md
> +如果发现没有名称为 V2Ray 的容器，可以查看所有容器：
```suggestion
如果发现没有名称为 v2ray 的容器，可以查看所有容器：
```

2020-12-20 17:09 UTC, nicholascw commented on zh_CN/app/docker-deploy-v2ray.md
> -#### 更新历史
Add the revision history back plz

2020-12-21 23:20 UTC, nicholascw approved these changes

2020-12-30 02:25 UTC, closed without merging